// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: proto/my_option.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyFileOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok *bool `protobuf:"varint,1,opt,name=ok,proto3,oneof" json:"ok,omitempty"`
}

func (x *MyFileOptions) Reset() {
	*x = MyFileOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_my_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyFileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyFileOptions) ProtoMessage() {}

func (x *MyFileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_my_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyFileOptions.ProtoReflect.Descriptor instead.
func (*MyFileOptions) Descriptor() ([]byte, []int) {
	return file_proto_my_option_proto_rawDescGZIP(), []int{0}
}

func (x *MyFileOptions) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

type MyMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok *bool `protobuf:"varint,1,opt,name=ok,proto3,oneof" json:"ok,omitempty"`
}

func (x *MyMessageOptions) Reset() {
	*x = MyMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_my_option_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMessageOptions) ProtoMessage() {}

func (x *MyMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_my_option_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMessageOptions.ProtoReflect.Descriptor instead.
func (*MyMessageOptions) Descriptor() ([]byte, []int) {
	return file_proto_my_option_proto_rawDescGZIP(), []int{1}
}

func (x *MyMessageOptions) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

var file_proto_my_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*MyFileOptions)(nil),
		Field:         51234,
		Name:          "my_option.my_file_option",
		Tag:           "bytes,51234,opt,name=my_file_option",
		Filename:      "proto/my_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MyMessageOptions)(nil),
		Field:         51234,
		Name:          "my_option.my_message_option",
		Tag:           "bytes,51234,opt,name=my_message_option",
		Filename:      "proto/my_option.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional my_option.MyFileOptions my_file_option = 51234;
	E_MyFileOption = &file_proto_my_option_proto_extTypes[0] // 取一个自定义不重复值
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional my_option.MyMessageOptions my_message_option = 51234;
	E_MyMessageOption = &file_proto_my_option_proto_extTypes[1] // 取一个自定义不重复值
)

var File_proto_my_option_proto protoreflect.FileDescriptor

var file_proto_my_option_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x4d, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x13, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x6f,
	0x6b, 0x22, 0x2e, 0x0a, 0x10, 0x4d, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x13, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x6f,
	0x6b, 0x3a, 0x61, 0x0a, 0x0e, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xa2, 0x90, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x79, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x6d, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x3a, 0x6d, 0x0a, 0x11, 0x6d, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa2, 0x90, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x0f, 0x6d, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x88, 0x01, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x6d, 0x79, 0x2d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_my_option_proto_rawDescOnce sync.Once
	file_proto_my_option_proto_rawDescData = file_proto_my_option_proto_rawDesc
)

func file_proto_my_option_proto_rawDescGZIP() []byte {
	file_proto_my_option_proto_rawDescOnce.Do(func() {
		file_proto_my_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_my_option_proto_rawDescData)
	})
	return file_proto_my_option_proto_rawDescData
}

var file_proto_my_option_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_my_option_proto_goTypes = []interface{}{
	(*MyFileOptions)(nil),               // 0: my_option.MyFileOptions
	(*MyMessageOptions)(nil),            // 1: my_option.MyMessageOptions
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_proto_my_option_proto_depIdxs = []int32{
	2, // 0: my_option.my_file_option:extendee -> google.protobuf.FileOptions
	3, // 1: my_option.my_message_option:extendee -> google.protobuf.MessageOptions
	0, // 2: my_option.my_file_option:type_name -> my_option.MyFileOptions
	1, // 3: my_option.my_message_option:type_name -> my_option.MyMessageOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_my_option_proto_init() }
func file_proto_my_option_proto_init() {
	if File_proto_my_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_my_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyFileOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_my_option_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_my_option_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_my_option_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_my_option_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_my_option_proto_goTypes,
		DependencyIndexes: file_proto_my_option_proto_depIdxs,
		MessageInfos:      file_proto_my_option_proto_msgTypes,
		ExtensionInfos:    file_proto_my_option_proto_extTypes,
	}.Build()
	File_proto_my_option_proto = out.File
	file_proto_my_option_proto_rawDesc = nil
	file_proto_my_option_proto_goTypes = nil
	file_proto_my_option_proto_depIdxs = nil
}
